---
title: "git_01"
author: "Rachel Gilpatrick"
date: "21 Sept. 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  
Beware the Jabberwock, my son!  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


I think there are poems greater and stranger than any I have known.   
I would like to find them.  
They are not on the greying paper of old books  
or chanted on obscure lips.  
They are not in the language of mermaids  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,    
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The whiskey stink of rot has settled  
in the garden, and a burst of fruit flies rises  
when I touch the dying tomato plants.  

Still, the claws of tiny yellow blossoms  
flail in the air as I pull the vines up by the roots  
and toss them in the compost.  

It feels cruel. Something in me isn’t ready  
to let go of summer so easily. To destroy  
what I’ve carefully cultivated all these months.  
Those pale flowers might still have time to fruit.  

My great-grandmother sang with the girls of her village  
as they pulled the flax. Songs so old  
and so tied to the season that the very sound  
seemed to turn the weather.  